### ISSUE TITLE
一人血书添加设置device的功能

### ISSUE THREAD

**Issue by U-uU** [m1dsolo/yangDL#1]

**Comment by m1dsolo** [comment]
You can select the device by setting the `CUDA_VISIBLE_DEVICES` environment variable before running the code, such as `CUDA_VISIBLE_DEVICES=1 python your_code.py` to use the second GPU. I will add the option to specify the device when adding the `DistributedDataParallel` in the future (I am not considering it now because I mainly only have one GPU).
